/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISuperfluidGovernanceInterface extends ethers.utils.Interface {
  functions: {
    "batchUpdateSuperTokenLogic(address,address[])": FunctionFragment;
    "clearConfig(address,address,bytes32)": FunctionFragment;
    "getConfigAsAddress(address,address,bytes32)": FunctionFragment;
    "getConfigAsUint256(address,address,bytes32)": FunctionFragment;
    "registerAgreementClass(address,address)": FunctionFragment;
    "replaceGovernance(address,address)": FunctionFragment;
    "setConfig(address,address,bytes32,address)": FunctionFragment;
    "updateContracts(address,address,address[],address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "batchUpdateSuperTokenLogic",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "clearConfig",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfigAsAddress",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfigAsUint256",
    values: [string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgreementClass",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "replaceGovernance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [string, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContracts",
    values: [string, string, string[], string]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateSuperTokenLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clearConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfigAsAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfigAsUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgreementClass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateContracts",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISuperfluidGovernance extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISuperfluidGovernanceInterface;

  functions: {
    batchUpdateSuperTokenLogic(
      host: string,
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "batchUpdateSuperTokenLogic(address,address[])"(
      host: string,
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    clearConfig(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "clearConfig(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { value: string }>;

    "getConfigAsAddress(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { value: string }>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    "getConfigAsUint256(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerAgreementClass(address,address)"(
      host: string,
      agreementClass: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "replaceGovernance(address,address)"(
      host: string,
      newGov: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setConfig(address,address,bytes32,address)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setConfig(address,address,bytes32,uint256)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateContracts(address,address,address[],address)"(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  batchUpdateSuperTokenLogic(
    host: string,
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "batchUpdateSuperTokenLogic(address,address[])"(
    host: string,
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  clearConfig(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "clearConfig(address,address,bytes32)"(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getConfigAsAddress(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getConfigAsAddress(address,address,bytes32)"(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getConfigAsUint256(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getConfigAsUint256(address,address,bytes32)"(
    host: string,
    superToken: string,
    key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  registerAgreementClass(
    host: string,
    agreementClass: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerAgreementClass(address,address)"(
    host: string,
    agreementClass: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  replaceGovernance(
    host: string,
    newGov: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "replaceGovernance(address,address)"(
    host: string,
    newGov: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setConfig(address,address,bytes32,address)"(
    host: string,
    superToken: string,
    key: BytesLike,
    value: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setConfig(address,address,bytes32,uint256)"(
    host: string,
    superToken: string,
    key: BytesLike,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateContracts(
    host: string,
    hostNewLogic: string,
    agreementClassNewLogics: string[],
    superTokenFactoryNewLogic: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateContracts(address,address,address[],address)"(
    host: string,
    hostNewLogic: string,
    agreementClassNewLogics: string[],
    superTokenFactoryNewLogic: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    batchUpdateSuperTokenLogic(
      host: string,
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchUpdateSuperTokenLogic(address,address[])"(
      host: string,
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    clearConfig(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "clearConfig(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getConfigAsAddress(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getConfigAsUint256(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerAgreementClass(address,address)"(
      host: string,
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<void>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "replaceGovernance(address,address)"(
      host: string,
      newGov: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setConfig(address,address,bytes32,address)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setConfig(address,address,bytes32,uint256)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateContracts(address,address,address[],address)"(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    batchUpdateSuperTokenLogic(
      host: string,
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "batchUpdateSuperTokenLogic(address,address[])"(
      host: string,
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    clearConfig(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "clearConfig(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getConfigAsAddress(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getConfigAsUint256(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerAgreementClass(address,address)"(
      host: string,
      agreementClass: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "replaceGovernance(address,address)"(
      host: string,
      newGov: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setConfig(address,address,bytes32,address)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setConfig(address,address,bytes32,uint256)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateContracts(address,address,address[],address)"(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchUpdateSuperTokenLogic(
      host: string,
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "batchUpdateSuperTokenLogic(address,address[])"(
      host: string,
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    clearConfig(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "clearConfig(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getConfigAsAddress(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getConfigAsAddress(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConfigAsUint256(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getConfigAsUint256(address,address,bytes32)"(
      host: string,
      superToken: string,
      key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerAgreementClass(
      host: string,
      agreementClass: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerAgreementClass(address,address)"(
      host: string,
      agreementClass: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    replaceGovernance(
      host: string,
      newGov: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "replaceGovernance(address,address)"(
      host: string,
      newGov: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setConfig(address,address,bytes32,address)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setConfig(address,address,bytes32,uint256)"(
      host: string,
      superToken: string,
      key: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateContracts(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateContracts(address,address,address[],address)"(
      host: string,
      hostNewLogic: string,
      agreementClassNewLogics: string[],
      superTokenFactoryNewLogic: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
